version: "3"
services:
  node:
    container_name: node
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
      - "4200:4200"
      - "8080:8080"
    command: sh